language: node_js
sudo: true
cache:
  directories:
  - node
node_js:
- 7.4.0
script:
-
before_deploy:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: EHsNTCSP7NFzDXrbTjmL0dWSflYEx97nKV8sxWXAYTHciAgd3v3fw8I1LWQV/D09Hi0aOUENAqkvLbfFq0pH99SCRtrnNj2X3bXm6fqKXtDHL6clHdP//QspwnDPLqDWn/eiUHKMGtQFlsssvMB6kHcBu3dSJE/UoIeOuTsYGATtWUbLR/M8pEeeB+Gat2NUFHpt8x7dbTCf0Y8v+6ZwyQl1T54ZrQsoKrMsHMevrwi5KA+eoV9JolFmXLqDnxCweJ5ifYDO9jOXkPEHyvUUs9ieTx3WiHQqIvjTHzI4Rtije3FlXG8qu6dwux6qh4EhxGB10gAx/Hf7Rdpq8YJWQuKXvxOfhUsKDufp/vTDvC9HLImuAZ2aPACLNEElskAPyAiLH3Z9y4IQIUJvPrZHM0FrOoDC4LmKK4A1+47FBHwBM/aXdASeGSAxWzfqRaAnBhBLdgqV30h314sOJWt+wtq4mgnDosZ8TQOidQhtsljUFZM40wZdaoSoSEJsiWjsZwtmAaLJRCQjbaUasP4xyi03xzU3CoNdm9T4/fz5pZpzI4PELIRNZkwVCDZQjRQj8RH34PNmED0yoPDxIWz/0I1ZxuOVI6lrX8spzRfRRcl2DzfjrtHqq0VT4YV3S1kYtUYAXtedSFQpb4g0VXwhEKrBHvlQbfOpXrQ77s4SszY=
  local_dir: build
  keep-history: true
  on:
    branch:
    - master
notifications:
  on_success: change
  on_failure: always
env:
  global:
