language: node_js
sudo: true
cache:
  directories:
  - node
node_js:
- 7.4.0
script:
-
before_deploy:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  keep-history: true
  on:
    branch:
    - master
  github_token:
    secure: U1/iR0xiJUPXlQajs+6tWLUwc+IOV7OM8urNDBIFtvJTNvcul45OhLf2IxVLskSovrJVuINUGiK96X/7ov8hc9v0fHfFx9DwcBpeyPLXSa/X2WAnZQeSWV/LilmLj/UrKwt5yXJfxAVi61FQj4N+rdvpyAJqPzx5KAMcaFhaBRniFjJV3vfOZJNAmNsMyafA5/O8SDiSjWn+a/D9g/P+zWBaBcmz8Sc8nRXXlFlUhdH/xDRgtGmpU4eW7KrUXIQyRTLAu2a32HmSi+SG9P7SNEIUWrCvxw4Y2oYrizMQ1hRLznzO1ooNsD8SUjbWACEErfEwfmtHe1nhm0EQg8lKTtLAyjTAuvYmDp8mQW+CVbZMDqe9I9ogzJOsz+S48wo28qgb/2KL+BEfTGkSNelZc3jnPUaF62aFZUhQYc7BYsca1UxJK4xNO69YgO2EQLB6TT1VU+XdHd/942sdynyTACX33R5Ih57HH3yu2xkluaj+GYSshe2TdmziL0PR131DZI7P+4Mz6W7NGJuAkoL88NemlhfjviaYX3qLuePjTyYCEgXW8fW9u6SDHHrkfMAL+Urpa+EeEtayG2p5XbVAx959m88Y/BBlcxQw5R4MgiipwnZPTbQGjsa0a50WmjbWw1G4UOvpYEARaWYs+wvwIdc9Pmzh9zcXVyzCpVI4A58=
notifications:
  on_success: change
  on_failure: always
